import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, FileText, Globe2, Loader2, Radar, Search, UploadCloud } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Empty, Panel, Pill, StatCard } from "@/components/statbridge/desk-ui";
import { StaffShell } from "@/components/statbridge/StaffShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { runKnowledgeCrawl } from "@/lib/statbridge/crawl.functions";
import { decideKnowledgeSource, ingestKnowledgeFile, ingestKnowledgeUrl, listKnowledgeSources } from "@/lib/statbridge/knowledge.functions";
import { useStaff } from "@/lib/staff/useStaff";

const title="Knowledge library — StatBridge staff";
export const Route=createFileRoute("/staff/knowledge/sources")({head:()=>({meta:[{title},{name:"robots",content:"noindex"}]}),component:SourcesPage});
const input="w-full rounded-md border border-border bg-surface px-3 py-2 text-sm";
type Meta={title:string;publisher:string;sourceType:"statistical_release"|"media_release"|"methodology"|"organisational_page"|"faq_page"|"other";topic:string;publishedOn:string;referencePeriod:string};
const blank:Meta={title:"",publisher:"Statistics South Africa",sourceType:"statistical_release",topic:"",publishedOn:"",referencePeriod:""};

function SourcesPage(){
 const {profile,hasPermission}=useStaff(); const qc=useQueryClient(); const [tab,setTab]=useState<"file"|"url">("file"); const [meta,setMeta]=useState(blank); const [url,setUrl]=useState(""); const [file,setFile]=useState<File|null>(null); const [search,setSearch]=useState("");
 const fetchList=useServerFn(listKnowledgeSources), ingestFile=useServerFn(ingestKnowledgeFile), ingestUrl=useServerFn(ingestKnowledgeUrl), decide=useServerFn(decideKnowledgeSource);
 const list=useQuery({queryKey:["knowledge-library"],queryFn:()=>fetchList()}); const refresh=()=>qc.invalidateQueries({queryKey:["knowledge-library"]});
 const ingestion=useMutation({mutationFn:async()=>{if(tab==="url")return ingestUrl({data:{...meta,url}}); if(!file||!profile)throw new Error("Choose a file first."); const path=`${profile.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`; const up=await supabase.storage.from("knowledge-files").upload(path,file,{upsert:false}); if(up.error)throw new Error(up.error.message); return ingestFile({data:{...meta,storagePath:path,fileName:file.name,mimeType:file.type||"application/octet-stream",fileSize:file.size}});},onSuccess:r=>{toast.success(`${r.passages} extracts created. Review before approval.`);setMeta(blank);setUrl("");setFile(null);void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const action=useMutation({mutationFn:(d:{versionId:string;action:"approve"|"reject"|"withdraw";reason?:string})=>decide({data:d}),onSuccess:()=>{toast.success("Source register updated.");void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const crawl=useMutation({mutationFn:()=>runKnowledgeCrawl(),onSuccess:r=>{toast.success(`Crawler proposed ${r.inserted.length} new publications.`);void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const rows=useMemo(()=>((list.data??[]) as any[]).filter(v=>`${v.sources?.title} ${v.sources?.publisher} ${v.sources?.topic} ${v.version_label}`.toLowerCase().includes(search.toLowerCase())),[list.data,search]);
 const pending=rows.filter(r=>r.status==="pending").length, failed=rows.filter(r=>r.job?.state==="failed").length;
 return <StaffShell title="Knowledge library"><div className="space-y-5">
  <div><p className="max-w-3xl text-sm text-muted-foreground">Bring official South African publications into a controlled pipeline: capture, extract, inspect, verify and approve. Extracted text stays private and cannot answer public questions until approval.</p></div>
  <div className="grid gap-3 sm:grid-cols-4"><StatCard label="Versions" value={rows.length}/><StatCard label="Awaiting review" value={pending} tone={pending?"warn":"default"}/><StatCard label="Failed jobs" value={failed} tone={failed?"warn":"default"}/><StatCard label="Searchable extracts" value={rows.reduce((n,r)=>n+r.counts.passages,0)}/></div>
  {hasPermission("sources.upload")&&<Panel title="Add knowledge" description="PDF, Word, Markdown, text, CSV, Excel, or an approved official South African URL.">
   <div className="mb-4 flex gap-2"><Button type="button" variant={tab==="file"?"default":"outline"} onClick={()=>setTab("file")}><UploadCloud/>Upload file</Button><Button type="button" variant={tab==="url"?"default":"outline"} onClick={()=>setTab("url")}><Globe2/>Official URL</Button></div>
   <form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();ingestion.mutate();}}>
    <label className="text-xs font-medium">Publication title<input required className={`${input} mt-1`} value={meta.title} onChange={e=>setMeta({...meta,title:e.target.value})}/></label>
    <label className="text-xs font-medium">Publisher<input required className={`${input} mt-1`} value={meta.publisher} onChange={e=>setMeta({...meta,publisher:e.target.value})}/></label>
    <label className="text-xs font-medium">Source type<select className={`${input} mt-1`} value={meta.sourceType} onChange={e=>setMeta({...meta,sourceType:e.target.value as Meta["sourceType"]})}><option value="statistical_release">Statistical release</option><option value="media_release">Media release</option><option value="methodology">Methodology</option><option value="organisational_page">Organisational page</option><option value="faq_page">FAQ page</option><option value="other">Other official source</option></select></label>
    <label className="text-xs font-medium">Topic<input className={`${input} mt-1`} placeholder="Labour market, population…" value={meta.topic} onChange={e=>setMeta({...meta,topic:e.target.value})}/></label>
    <label className="text-xs font-medium">Published date<input type="date" className={`${input} mt-1`} value={meta.publishedOn} onChange={e=>setMeta({...meta,publishedOn:e.target.value})}/></label>
    <label className="text-xs font-medium">Reference period<input className={`${input} mt-1`} placeholder="Q2 2026" value={meta.referencePeriod} onChange={e=>setMeta({...meta,referencePeriod:e.target.value})}/></label>
    <label className="text-xs font-medium md:col-span-2">{tab==="file"?"Document":"Official URL"}{tab==="file"?<input required type="file" accept=".pdf,.docx,.md,.txt,.csv,.xls,.xlsx" className={`${input} mt-1`} onChange={e=>setFile(e.target.files?.[0]??null)}/>:<input required type="url" className={`${input} mt-1`} placeholder="https://www.statssa.gov.za/..." value={url} onChange={e=>setUrl(e.target.value)}/>}</label>
    <div className="md:col-span-2"><Button disabled={ingestion.isPending}>{ingestion.isPending&&<Loader2 className="animate-spin"/>}{ingestion.isPending?"Extracting securely…":"Add and extract"}</Button></div>
   </form>
  </Panel>}
  <Panel title="Official source monitor" description="Discovery creates pending records only; it never bypasses human approval." action={hasPermission("crawler.manage")?<Button variant="outline" onClick={()=>crawl.mutate()} disabled={crawl.isPending}><Radar/>{crawl.isPending?"Running…":"Run crawler"}</Button>:null}><p className="text-sm text-muted-foreground">Monitor approved South African publishers for changed and newly published material.</p></Panel>
  <Panel title="Source register" description="Every version retains provenance, extraction health and approval state." action={<div className="relative"><Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground"/><input className={`${input} w-64 pl-8`} placeholder="Search sources" value={search} onChange={e=>setSearch(e.target.value)}/></div>}>
   {list.isLoading?<p className="flex items-center gap-2 py-8 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>Loading the controlled register…</p>:list.isError?<p className="rounded border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">The register could not be loaded: {(list.error as Error).message}</p>:!rows.length?<Empty>No matching knowledge sources.</Empty>:<div className="space-y-3">{rows.map((v:any)=><SourceCard key={v.id} row={v} canDecide={hasPermission("sources.approve")} busy={action.isPending} act={(a,r)=>action.mutate(r===undefined?{versionId:v.id,action:a}:{versionId:v.id,action:a,reason:r})}/>)}</div>}
  </Panel>
 </div></StaffShell>;
}

function SourceCard({row,canDecide,busy,act}:{row:any;canDecide:boolean;busy:boolean;act:(a:"approve"|"reject"|"withdraw",r?:string)=>void}){const [reason,setReason]=useState("");const tone=row.status==="approved"?"good":row.status==="rejected"||row.job?.state==="failed"?"bad":row.status==="pending"?"warn":"muted";return <article className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><FileText className="size-4 text-accent"/><h3 className="font-medium">{row.sources?.title}</h3><Pill tone={tone}>{row.status}</Pill><Pill>{row.job?.state??row.ingest_state}</Pill></div><p className="mt-1 text-xs text-muted-foreground">{row.sources?.publisher} · {row.sources?.source_type?.replaceAll("_"," ")} · {row.version_label}</p></div><div className="grid grid-cols-3 gap-4 text-center text-xs"><div><b className="block text-base">{row.counts.passages}</b>extracts</div><div><b className="block text-base">{row.counts.figures}</b>figures</div><div><b className="block text-base">{row.counts.verified}</b>verified</div></div></div>{row.ingest_note&&<p className="mt-3 rounded bg-secondary/60 p-2 text-xs text-muted-foreground">{row.ingest_note}</p>}{row.job?.error_message&&<p className="mt-3 rounded bg-destructive/5 p-2 text-xs text-destructive">{row.job.error_message}</p>}{row.original_url&&<a className="mt-2 inline-block text-xs text-accent underline" href={row.original_url} target="_blank" rel="noreferrer">Open original source</a>}{canDecide&&<div className="mt-3 flex flex-wrap gap-2">{row.status==="pending"&&<Button size="sm" disabled={busy||!row.counts.passages} onClick={()=>act("approve")}>Approve version</Button>}<input className={`${input} min-w-48 flex-1`} placeholder="Reason for rejection or withdrawal" value={reason} onChange={e=>setReason(e.target.value)}/>{row.status==="pending"&&<Button size="sm" variant="destructive" disabled={busy||reason.length<3} onClick={()=>act("reject",reason)}>Reject</Button>}{row.status==="approved"&&<Button size="sm" variant="outline" disabled={busy||reason.length<3} onClick={()=>act("withdraw",reason)}>Withdraw</Button>}</div>}</article>}