import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ShieldCheck,UserPlus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Empty,Loading,Panel,Pill,relativeTime } from "@/components/statbridge/desk-ui";
import { StaffShell } from "@/components/statbridge/StaffShell";
import { Button } from "@/components/ui/button";
import { createRole,getStaffAdministration,inviteStaff,setStaffActive,setStaffRoles } from "@/lib/statbridge/admin.functions";
import { useStaff } from "@/lib/staff/useStaff";

export const Route=createFileRoute("/staff/team")({head:()=>({meta:[{title:"Staff and roles — StatBridge"},{name:"robots",content:"noindex"}]}),component:TeamPage});
const field="w-full rounded-md border border-border bg-surface px-3 py-2 text-sm";
function TeamPage(){
 const {profile,hasPermission}=useStaff(),qc=useQueryClient();const fetch=useServerFn(getStaffAdministration),invite=useServerFn(inviteStaff),assign=useServerFn(setStaffRoles),toggle=useServerFn(setStaffActive),addRole=useServerFn(createRole);
 const query=useQuery({queryKey:["staff-admin"],queryFn:()=>fetch()});const refresh=()=>qc.invalidateQueries({queryKey:["staff-admin"]});
 const [inv,setInv]=useState({fullName:"",email:"",roleIds:[] as string[]});const [role,setRole]=useState({name:"",description:"",permissionKeys:[] as string[]});
 const invitation=useMutation({mutationFn:()=>invite({data:inv}),onSuccess:()=>{toast.success("Invitation sent securely.");setInv({fullName:"",email:"",roleIds:[]});void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const roles=useMutation({mutationFn:(d:{staffId:string;roleIds:string[]})=>assign({data:d}),onSuccess:()=>{toast.success("Role assignment updated.");void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const active=useMutation({mutationFn:(d:{staffId:string;isActive:boolean;reason:string})=>toggle({data:d}),onSuccess:()=>{toast.success("Account status updated and sessions revoked where required.");void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const create=useMutation({mutationFn:()=>addRole({data:role}),onSuccess:()=>{toast.success("Custom role created.");setRole({name:"",description:"",permissionKeys:[]});void refresh();},onError:(e:Error)=>toast.error(e.message)});
 const data=query.data;
 return <StaffShell title="Staff and roles"><div className="space-y-5">
  <p className="max-w-3xl text-sm text-muted-foreground">Invite staff without sharing passwords, assign one or more roles, promote or demote access, and suspend accounts with an audit reason. The final active Super Administrator is protected.</p>
  {query.isLoading?<Loading/>:query.isError?<p className="rounded border border-destructive/30 p-3 text-sm text-destructive">{(query.error as Error).message}</p>:<>
   <Panel title="Role catalogue" description="System roles are maintained by StatBridge. Custom roles can combine precise permissions."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data?.roles.map(r=><article key={r.id} className="rounded border border-border p-3"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-accent"/><b className="text-sm">{r.name}</b>{r.isSystem&&<Pill>System</Pill>}</div><p className="mt-1 text-xs text-muted-foreground">{r.description}</p><p className="mt-2 text-xs font-medium">{r.permissions.length} permissions</p></article>)}</div></Panel>
   {hasPermission("roles.manage")&&<Panel title="Create a custom role" description="Choose only the capabilities this job needs."><form onSubmit={e=>{e.preventDefault();create.mutate();}} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input required className={field} placeholder="Role name" value={role.name} onChange={e=>setRole({...role,name:e.target.value})}/><input className={field} placeholder="Purpose and boundaries" value={role.description} onChange={e=>setRole({...role,description:e.target.value})}/></div><PermissionGrid permissions={data?.permissions??[]} selected={role.permissionKeys} setSelected={v=>setRole({...role,permissionKeys:v})}/><Button disabled={create.isPending||!role.permissionKeys.length}>Create role</Button></form></Panel>}
   {hasPermission("staff.manage")&&<Panel title="Invite a colleague" description="They receive an email link and choose their own password; no password is displayed or shared."><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();invitation.mutate();}}><input required className={field} placeholder="Full name" value={inv.fullName} onChange={e=>setInv({...inv,fullName:e.target.value})}/><input required type="email" className={field} placeholder="Work email" value={inv.email} onChange={e=>setInv({...inv,email:e.target.value})}/><div className="sm:col-span-2"><RoleChecks roles={data?.roles??[]} selected={inv.roleIds} setSelected={v=>setInv({...inv,roleIds:v})}/></div><div className="sm:col-span-2"><Button disabled={invitation.isPending||!inv.roleIds.length}><UserPlus/>{invitation.isPending?"Sending…":"Send invitation"}</Button></div></form></Panel>}
   <Panel title="People with access" description="Role changes take effect immediately.">{!data?.staff.length?<Empty>No staff accounts.</Empty>:<div className="space-y-3">{data.staff.map(m=><StaffRow key={m.id} member={m} allRoles={data.roles} own={m.id===profile?.id} canManage={hasPermission("roles.manage")} onRoles={ids=>roles.mutate({staffId:m.id,roleIds:ids})} onStatus={(isActive,reason)=>active.mutate({staffId:m.id,isActive,reason})}/>)}</div>}</Panel>
   <Panel title="Pending invitations">{!data?.invitations.length?<Empty>No invitations recorded.</Empty>:<div className="divide-y divide-border">{data.invitations.slice(0,20).map((i:any)=><div key={i.id} className="flex flex-wrap justify-between gap-2 py-2 text-sm"><span><b>{i.full_name}</b> · {i.email}</span><span className="text-muted-foreground">{i.status} · {relativeTime(i.created_at)}</span></div>)}</div>}</Panel>
  </>}</div></StaffShell>;
}
function PermissionGrid({permissions,selected,setSelected}:{permissions:any[];selected:string[];setSelected:(v:string[])=>void}){const groups=permissions.reduce<Record<string,any[]>>((all,p)=>{(all[p.groupName]??=[]).push(p);return all},{});return <div className="grid gap-3 lg:grid-cols-3">{Object.entries(groups).map(([name,items])=><fieldset key={name} className="rounded border border-border p-3"><legend className="px-1 text-xs font-semibold">{name}</legend>{items.map(p=><label key={p.key} className="flex gap-2 py-1 text-xs"><input type="checkbox" checked={selected.includes(p.key)} onChange={e=>setSelected(e.target.checked?[...selected,p.key]:selected.filter(x=>x!==p.key))}/><span><b>{p.name}</b><span className="block text-muted-foreground">{p.description}</span></span></label>)}</fieldset>)}</div>}
function RoleChecks({roles,selected,setSelected}:{roles:any[];selected:string[];setSelected:(v:string[])=>void}){return <div className="flex flex-wrap gap-2">{roles.filter(r=>r.isActive).map(r=><label key={r.id} className="flex items-center gap-2 rounded border border-border px-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/>{r.name}</label>)}</div>}
function StaffRow({member,allRoles,own,canManage,onRoles,onStatus}:{member:any;allRoles:any[];own:boolean;canManage:boolean;onRoles:(v:string[])=>void;onStatus:(a:boolean,r:string)=>void}){const [ids,setIds]=useState<string[]>(member.roles.map((r:any)=>r.id));return <article className="rounded border border-border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{member.fullName} {own&&<Pill>You</Pill>}</p><p className="text-xs text-muted-foreground">{member.email??"No email"} · last sign-in {relativeTime(member.lastSignInAt)}</p><div className="mt-2 flex flex-wrap gap-1">{member.roles.map((r:any)=><Pill key={r.id} tone={r.key==="super_administrator"?"warn":"muted"}>{r.name}</Pill>)}</div></div><Pill tone={member.isActive?"good":"bad"}>{member.isActive?"Active":"Suspended"}</Pill></div>{canManage&&!own&&<div className="mt-3 space-y-2"><RoleChecks roles={allRoles} selected={ids} setSelected={setIds}/><div className="flex gap-2"><Button size="sm" disabled={!ids.length} onClick={()=>onRoles(ids)}>Save roles</Button><Button size="sm" variant="outline" onClick={()=>{const reason=prompt(member.isActive?"Reason for suspension":"Reason for restoration");if(reason)onStatus(!member.isActive,reason)}}>{member.isActive?"Suspend":"Restore"}</Button></div></div>}</article>}