/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as MediaRouteImport } from './routes/media'
import { Route as CaseIndexRouteImport } from './routes/case.index'
import { Route as CaseRefRouteImport } from './routes/case.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIndexRoute = CaseIndexRouteImport.update({
  id: '/case/',
  path: '/case/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRefRoute = CaseRefRouteImport.update({
  id: '/case/$ref',
  path: '/case/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/case/': typeof CaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/case': typeof CaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/case/': typeof CaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/developers' | '/embed' | '/media' | '/case/$ref' | '/case/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/developers' | '/embed' | '/media' | '/case/$ref' | '/case'
  id:
    | '__root__'
    | '/'
    | '/developers'
    | '/embed'
    | '/media'
    | '/case/$ref'
    | '/case/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopersRoute: typeof DevelopersRoute
  EmbedRoute: typeof EmbedRoute
  MediaRoute: typeof MediaRoute
  CaseRefRoute: typeof CaseRefRoute
  CaseIndexRoute: typeof CaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/': {
      id: '/case/'
      path: '/case'
      fullPath: '/case/'
      preLoaderRoute: typeof CaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$ref': {
      id: '/case/$ref'
      path: '/case/$ref'
      fullPath: '/case/$ref'
      preLoaderRoute: typeof CaseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopersRoute: DevelopersRoute,
  EmbedRoute: EmbedRoute,
  MediaRoute: MediaRoute,
  CaseRefRoute: CaseRefRoute,
  CaseIndexRoute: CaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
