/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as MediaRouteImport } from './routes/media'
import { Route as CaseIndexRouteImport } from './routes/case.index'
import { Route as CaseRefRouteImport } from './routes/case.$ref'
import { Route as StaffInsightsRouteImport } from './routes/staff/insights'
import { Route as StaffRecordRouteImport } from './routes/staff/record'
import { Route as StaffSignInRouteImport } from './routes/staff/sign-in'
import { Route as StaffKnowledgeGuidelinesRouteImport } from './routes/staff/knowledge.guidelines'
import { Route as StaffKnowledgeMemoryRouteImport } from './routes/staff/knowledge.memory'
import { Route as StaffKnowledgeSourcesRouteImport } from './routes/staff/knowledge.sources'
import { Route as StaffReviewIndexRouteImport } from './routes/staff/review.index'
import { Route as StaffReviewIdRouteImport } from './routes/staff/review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIndexRoute = CaseIndexRouteImport.update({
  id: '/case/',
  path: '/case/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRefRoute = CaseRefRouteImport.update({
  id: '/case/$ref',
  path: '/case/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInsightsRoute = StaffInsightsRouteImport.update({
  id: '/staff/insights',
  path: '/staff/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRecordRoute = StaffRecordRouteImport.update({
  id: '/staff/record',
  path: '/staff/record',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff/sign-in',
  path: '/staff/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffKnowledgeGuidelinesRoute =
  StaffKnowledgeGuidelinesRouteImport.update({
    id: '/staff/knowledge/guidelines',
    path: '/staff/knowledge/guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffKnowledgeMemoryRoute = StaffKnowledgeMemoryRouteImport.update({
  id: '/staff/knowledge/memory',
  path: '/staff/knowledge/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffKnowledgeSourcesRoute = StaffKnowledgeSourcesRouteImport.update({
  id: '/staff/knowledge/sources',
  path: '/staff/knowledge/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReviewIndexRoute = StaffReviewIndexRouteImport.update({
  id: '/staff/review/',
  path: '/staff/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReviewIdRoute = StaffReviewIdRouteImport.update({
  id: '/staff/review/$id',
  path: '/staff/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/desk': typeof DeskRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/staff/insights': typeof StaffInsightsRoute
  '/staff/record': typeof StaffRecordRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/case/': typeof CaseIndexRoute
  '/staff/knowledge/guidelines': typeof StaffKnowledgeGuidelinesRoute
  '/staff/knowledge/memory': typeof StaffKnowledgeMemoryRoute
  '/staff/knowledge/sources': typeof StaffKnowledgeSourcesRoute
  '/staff/review/$id': typeof StaffReviewIdRoute
  '/staff/review/': typeof StaffReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/desk': typeof DeskRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/staff/insights': typeof StaffInsightsRoute
  '/staff/record': typeof StaffRecordRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/case': typeof CaseIndexRoute
  '/staff/knowledge/guidelines': typeof StaffKnowledgeGuidelinesRoute
  '/staff/knowledge/memory': typeof StaffKnowledgeMemoryRoute
  '/staff/knowledge/sources': typeof StaffKnowledgeSourcesRoute
  '/staff/review/$id': typeof StaffReviewIdRoute
  '/staff/review': typeof StaffReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/desk': typeof DeskRoute
  '/developers': typeof DevelopersRoute
  '/embed': typeof EmbedRoute
  '/media': typeof MediaRoute
  '/case/$ref': typeof CaseRefRoute
  '/staff/insights': typeof StaffInsightsRoute
  '/staff/record': typeof StaffRecordRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/case/': typeof CaseIndexRoute
  '/staff/knowledge/guidelines': typeof StaffKnowledgeGuidelinesRoute
  '/staff/knowledge/memory': typeof StaffKnowledgeMemoryRoute
  '/staff/knowledge/sources': typeof StaffKnowledgeSourcesRoute
  '/staff/review/$id': typeof StaffReviewIdRoute
  '/staff/review/': typeof StaffReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/desk'
    | '/developers'
    | '/embed'
    | '/media'
    | '/case/$ref'
    | '/staff/insights'
    | '/staff/record'
    | '/staff/sign-in'
    | '/case/'
    | '/staff/knowledge/guidelines'
    | '/staff/knowledge/memory'
    | '/staff/knowledge/sources'
    | '/staff/review/$id'
    | '/staff/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/desk'
    | '/developers'
    | '/embed'
    | '/media'
    | '/case/$ref'
    | '/staff/insights'
    | '/staff/record'
    | '/staff/sign-in'
    | '/case'
    | '/staff/knowledge/guidelines'
    | '/staff/knowledge/memory'
    | '/staff/knowledge/sources'
    | '/staff/review/$id'
    | '/staff/review'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/desk'
    | '/developers'
    | '/embed'
    | '/media'
    | '/case/$ref'
    | '/staff/insights'
    | '/staff/record'
    | '/staff/sign-in'
    | '/case/'
    | '/staff/knowledge/guidelines'
    | '/staff/knowledge/memory'
    | '/staff/knowledge/sources'
    | '/staff/review/$id'
    | '/staff/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DeskRoute: typeof DeskRoute
  DevelopersRoute: typeof DevelopersRoute
  EmbedRoute: typeof EmbedRoute
  MediaRoute: typeof MediaRoute
  CaseRefRoute: typeof CaseRefRoute
  StaffInsightsRoute: typeof StaffInsightsRoute
  StaffRecordRoute: typeof StaffRecordRoute
  StaffSignInRoute: typeof StaffSignInRoute
  CaseIndexRoute: typeof CaseIndexRoute
  StaffKnowledgeGuidelinesRoute: typeof StaffKnowledgeGuidelinesRoute
  StaffKnowledgeMemoryRoute: typeof StaffKnowledgeMemoryRoute
  StaffKnowledgeSourcesRoute: typeof StaffKnowledgeSourcesRoute
  StaffReviewIdRoute: typeof StaffReviewIdRoute
  StaffReviewIndexRoute: typeof StaffReviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/': {
      id: '/case/'
      path: '/case'
      fullPath: '/case/'
      preLoaderRoute: typeof CaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$ref': {
      id: '/case/$ref'
      path: '/case/$ref'
      fullPath: '/case/$ref'
      preLoaderRoute: typeof CaseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/insights': {
      id: '/staff/insights'
      path: '/staff/insights'
      fullPath: '/staff/insights'
      preLoaderRoute: typeof StaffInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/record': {
      id: '/staff/record'
      path: '/staff/record'
      fullPath: '/staff/record'
      preLoaderRoute: typeof StaffRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/sign-in': {
      id: '/staff/sign-in'
      path: '/staff/sign-in'
      fullPath: '/staff/sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/knowledge/guidelines': {
      id: '/staff/knowledge/guidelines'
      path: '/staff/knowledge/guidelines'
      fullPath: '/staff/knowledge/guidelines'
      preLoaderRoute: typeof StaffKnowledgeGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/knowledge/memory': {
      id: '/staff/knowledge/memory'
      path: '/staff/knowledge/memory'
      fullPath: '/staff/knowledge/memory'
      preLoaderRoute: typeof StaffKnowledgeMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/knowledge/sources': {
      id: '/staff/knowledge/sources'
      path: '/staff/knowledge/sources'
      fullPath: '/staff/knowledge/sources'
      preLoaderRoute: typeof StaffKnowledgeSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/review/': {
      id: '/staff/review/'
      path: '/staff/review'
      fullPath: '/staff/review/'
      preLoaderRoute: typeof StaffReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/review/$id': {
      id: '/staff/review/$id'
      path: '/staff/review/$id'
      fullPath: '/staff/review/$id'
      preLoaderRoute: typeof StaffReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DeskRoute: DeskRoute,
  DevelopersRoute: DevelopersRoute,
  EmbedRoute: EmbedRoute,
  MediaRoute: MediaRoute,
  CaseRefRoute: CaseRefRoute,
  StaffInsightsRoute: StaffInsightsRoute,
  StaffRecordRoute: StaffRecordRoute,
  StaffSignInRoute: StaffSignInRoute,
  CaseIndexRoute: CaseIndexRoute,
  StaffKnowledgeGuidelinesRoute: StaffKnowledgeGuidelinesRoute,
  StaffKnowledgeMemoryRoute: StaffKnowledgeMemoryRoute,
  StaffKnowledgeSourcesRoute: StaffKnowledgeSourcesRoute,
  StaffReviewIdRoute: StaffReviewIdRoute,
  StaffReviewIndexRoute: StaffReviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
