CREATE POLICY "rate counters are server only" ON public.rate_counters FOR ALL TO authenticated USING (false) WITH CHECK (false);

REVOKE EXECUTE ON FUNCTION public.activate_guidelines(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.approve_draft(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.approve_source(uuid, public.approval_basis) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assign_case(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.correct_routing(uuid, public.case_kind, public.review_reason[], text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.erase_contacts() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.flag_source_change(uuid, public.void_reason, uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_staff_role(uuid, public.staff_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_staff(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.next_case_reference() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_case(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reject_source(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.release_draft(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.request_changes(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.require_role(public.staff_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.save_desk_settings(jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.save_draft(uuid, text, public.draft_format, public.reading_level, jsonb, text[], uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_knowledge_semantic(extensions.vector, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_memory(text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_observations(text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_observations_by_id(uuid[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_passages(text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_passages_by_id(uuid[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_role(uuid, public.staff_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.staff_role_of(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.start_review(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.withdraw_source(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.write_audit(uuid, text, text, uuid, uuid, text, text, jsonb, public.audit_origin) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.has_staff_role(uuid, public.staff_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_staff(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.staff_role_of(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activate_guidelines(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.approve_draft(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.approve_source(uuid, public.approval_basis) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.assign_case(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.correct_routing(uuid, public.case_kind, public.review_reason[], text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reject_case(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reject_source(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.release_draft(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_changes(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.save_desk_settings(jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.save_draft(uuid, text, public.draft_format, public.reading_level, jsonb, text[], uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_knowledge_semantic(extensions.vector, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.search_memory(text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_observations(text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_observations_by_id(uuid[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_passages(text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_passages_by_id(uuid[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_role(uuid, public.staff_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.start_review(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.withdraw_source(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.erase_contacts() TO service_role;
GRANT EXECUTE ON FUNCTION public.flag_source_change(uuid, public.void_reason, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.next_case_reference() TO service_role;
GRANT EXECUTE ON FUNCTION public.require_role(public.staff_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.write_audit(uuid, text, text, uuid, uuid, text, text, jsonb, public.audit_origin) TO service_role;